version: '3.8'

networks:
  my_network:
      name: my_network
      external: true

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
          - my_network
  backend:
    build: ../../IdeaProjects/quiz-back
    ports:
      - "8081:8081"
    networks:
      - my_network



